### ISSUE TITLE
data released on thredds.met.no

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Geophone_Logger#1]
@jvoermans , the data are now available on thredds.met.no :)

https://thredds.met.no/thredds/catalog/metusers/jeanr/data_papers/vibration_data_sea_ice_2022/catalog.html

I checked the checksums, all looks good, but let me know if you have any comments :) . So you can add the link on the readme of this repository :) .

I will start the process of moving this to adc.met.no which is even better (guaranteed archiving "forever", and doi, metadata discovery, etc), but that may take weeks to months.

**Comment by jvoermans** [comment]
Perfect, thanks for the work!
