### ISSUE TITLE
move data to adc.met.no

### ISSUE THREAD

**Issue by jerabaul29** [jvoermans/Geophone_Logger#2]
TODO @jerabaul29

**Comment by jerabaul29** [comment]
an update: moving from thredds to adc is ongoing :) .

**Comment by jerabaul29** [comment]
@jvoermans the data are now available on adc.met.no long term archiving :) . Can you replace the link to the data in the paper to:

https://adc.met.no/datasets/10.21343/5vhg-a209

and possibly add a citation to the dataset in the paper at the same time so it gets recorded by reference counters (this is how adc.met.no tracks scientific use of the data for making statistics):

```
DOI https://doi.org/10.21343/5vhg-a209
Citation

Voermans, J., Rabault, J., Marchenko, A., Nose, T., Waseda, T., & Babanin, A. (2023). Geophone and Hydrophone deployments is Svalbard for 2022 [Data set]. Norwegian Meteorological Institute. https://doi.org/10.21343/5VHG-A209
```

**Comment by jerabaul29** [comment]
(note there is a typo: "is" should be "in" in the title, this will be corrected soon :) ).

**Comment by jerabaul29** [comment]
(this is already updated in the readme :) ).

**Comment by jvoermans** [comment]
Perfect! Thanks.

I'll add the link in the revised paper version too :)
I think I have to ask for two-week extension as overloaded with work.

**Comment by jerabaul29** [comment]
Sounds good :) . Let me know if there is anything I can do to help :) .
